export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readMinutes: number;
  category: string;
  body: string[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "mahalia-cassidy-fittest-player",
    title:
      "Mahalia Cassidy: One of the fittest players in Suncorp Super Netball",
    excerpt:
      "An interview with one of the league's hardest-running mid-courters on the work ethic behind her engine.",
    date: "2021-11-04",
    readMinutes: 4,
    category: "Athlete spotlight",
    body: [
      "Mahalia Cassidy plays Centre and Wing Defence with the Sunshine Coast Lightning and is regarded as one of the fittest players in the Suncorp Super Netball competition.",
      "Mahalia is described by her teammates as a 'workhorse'. She is consistent, never gives up and is safe with the ball in hand.",
      "## How would you describe the role of Centre in a team?",
      "The centre role is the primary connection linking the attack end to the defence end and back again. The centre works in close partnership with the Wing Defence to apply pressure on attackers and slow ball movement for the circle defence. In offensive situations, the centre fills a trailing and supporting role with the Wing Attack while delivering passes to shooters in the circle.",
      "## What is your favourite thing about playing Centre?",
      "Mahalia describes a love-hate relationship with the repeated efforts required in the position. She values being involved across the entire court and making an impact throughout gameplay.",
      "## Training intensity and game day performance",
      "Mahalia approaches training with high intensity and energy, believing this translates directly into match performance through habit formation. She acknowledges difficult training days when fatigued or sleep-deprived, and emphasises the importance of perseverance and drawing energy from teammates during challenging sessions.",
      "## Off-season fitness",
      "Previously, her off-seasons involved knee rehabilitation from injuries. In a recent off-season with extended time away from netball, she focused on strength and power training for injury prevention while maintaining flexibility through pilates, walking, and recreational riding.",
      "## Favourite quote",
      '"Work and you\'ll get what you need; work harder and you\'ll get what you want."',
    ],
  },
  {
    slug: "recovery-nutrition-101",
    title: "Recovery nutrition 101 for netball athletes",
    excerpt:
      "Practical post-game nutrition for developing players. What to eat, when, and why it matters more than supplements.",
    date: "2021-12-05",
    readMinutes: 5,
    category: "Performance",
    body: [
      "There's a lot of information available on what foods to consume both before and during exercise, but what should you do after? Does it really matter? Yes, it absolutely does. By prioritising recovery nutrition you will be stronger, faster and won't hit that post-training slump.",
      "So what are the basics of recovery nutrition?",
      "We summarise recovery nutrition by the 3 Rs: repair, refuel, rehydrate.",
      "## Repair",
      "Muscles get damaged during exercise. That's how they get stronger. Protein is an important nutrient to assist the repair process. Examples of protein-rich foods include meat, chicken, fish, eggs, legumes (chickpeas, beans, lentils), tofu and tempeh. Protein is also found in dairy foods such as milk and yoghurt. You want to have a good quality protein meal within 1 hour of finishing training. Grabbing a high-protein yoghurt, two eggs, or a glass of milk can get the repair started.",
      "## Refuel",
      "During exercise you expend energy. Post-training you now need to replenish energy so the protein can go to the muscles. Carbohydrates are what you need for this job. Carbohydrate-rich foods include breads and cereals, fruit, and starchy vegetables. So adding a banana to your yoghurt, toast to the eggs, or Milo to the milk will provide carbohydrates after training.",
      "## Rehydrate",
      "Exercise and high-intensity training induce sweating, so it's extremely important to keep hydrated during and after training. Dehydration impacts your concentration, speed, and ability to perform well. It also slows recovery. Drink plenty of fluids post-training, carry a bottle with you and keep sipping. Sports drinks are not needed post-exercise. Plain water is a great rehydration solution.",
      "## The 4th R: rest",
      "Make sure you're giving your body sufficient rest, both by getting good quality sleep at night (8-10 hours) and by having 1-2 days off per week. Muscles rebuild and recover at rest, so by resting, you're actually allowing your body to get stronger, faster and more powerful, ready for the next game.",
      "By covering all four Rs, you'll get the most out of your training. How much of each is dependent on your body, your training load (all sporting activities need to be considered) and other factors in your life. If you're hitting the 4Rs and still struggling, see a Sports Dietitian to refine your nutrition and identify other strategies to assist your performance.",
    ],
  },
  {
    slug: "rise-of-reilley-batcheldor",
    title: "The rise of Reilley Batcheldor",
    excerpt:
      "How a junior Diamonds prospect built her game from the ground up. Drills, mindset, and the lessons inside her path.",
    date: "2022-02-24",
    readMinutes: 4,
    category: "Athlete spotlight",
    body: [
      "Keep an eye on this name. Reilley Batcheldor will be a future Australian Diamond. This up-and-coming Goal Attack has signed with Sunshine Coast Lightning for the 2022 Suncorp Super Netball season.",
      "Reilley will be mentored by fellow Australian shooters Steph Wood and Cara Koenen.",
      "Reilley's rise has been no easy feat. She suffered an ACL injury in 2019, successfully completed her rehabilitation, and returned to court having a stellar 2021 season with QUT Netball in Netball Queensland's HART Sapphire Series.",
      "## How were you told you were offered a contract from Sunshine Coast Lightning?",
      "I received a phone call from head coach Kylee Byrne. She said she was impressed with my attitude and how I played throughout the year. I was so stoked to receive that phone call. I never expected it this soon in my career.",
      "## What are you looking forward to most about 2022?",
      "I'm looking forward to meeting all the players and playing with two Aussie Diamond shooters in Cara and Steph. I'll learn heaps and have so many great opportunities.",
      "## What advice do you have for young players aspiring to play in the Suncorp Super Netball?",
      "All the extra work you do behind the scenes is the work that counts. And every setback is an opportunity to take a step up.",
      "## Favourite quote",
      '"Hard work beats talent when talent doesn\'t work hard."',
    ],
  },
  {
    slug: "how-to-prepare-for-netball-trials",
    title: "How to prepare for netball trials (without losing your head)",
    excerpt:
      "What to focus on in the weeks before trials, what to ignore, and how to walk into the gym ready to be picked.",
    date: "2026-05-04",
    readMinutes: 6,
    category: "Mindset",
    body: [
      "Trials are stressful. You spend months training, then get judged on a single session by coaches who barely know your name. I've sat on both sides of that line. I missed every Victorian state team I trialled for as a bottom-age athlete, then later played for Australia. Here's what I learned.",
      "## Train the way you want to play",
      "The biggest shift in my own game happened when I stopped coasting through training and started training at the pace I needed to play. Trials are won in the months before, not on the day. If you've practised at 70 percent intensity, you can't suddenly perform at 100 percent in the trial. The body doesn't work that way.",
      "Two weeks before trials, audit your last three sessions. Did you go at full game pace on every drill? Did you communicate? Did you finish strong? If not, that's where to start.",
      "## Know exactly what they're looking for",
      "Selectors look at three things: your skill, your work rate, and your decision making under pressure. Skill is what gets you to the trial. Work rate and decision making are what get you selected.",
      "If you know your skill is solid, stop drilling skills the week of trials. Spend the time playing small-sided games where you have to read the play and make calls under fatigue. That's the muscle they're testing.",
      "## The day itself",
      "Eat what you normally eat. Wear what you normally wear. Don't try anything new. The day of trials is the wrong day for new shoes, new socks, new pre-game meals.",
      "Get there early. Move properly in your warm-up. Find one or two players you don't know and introduce yourself. Coaches notice the athletes who can connect with strangers fast. That's a leadership signal that has nothing to do with skill.",
      "## When they call your group",
      "Talk. Constantly. To your team, to the umpire, to yourself if no one else is listening. Coaches are watching for athletes who organise the people around them. Even simple calls like 'I'm with you', 'I've got the player on the post', or 'good ball' are noticed.",
      "Make a mistake? Reset in two seconds and go again. Coaches do not select athletes who hold onto errors.",
      "## After the result",
      "If you get selected, well done. The work changes from getting in to staying in. If you don't, do not stop playing. I missed my first three Victorian state trials as a bottom-age athlete and went on to play for Australia. Non-selection is information, not a verdict.",
      "Ask the coach for one thing to work on. Most coaches will give you a real answer if you ask without ego. Then go and work on it for the next twelve months. That's the path.",
    ],
  },
  {
    slug: "parents-guide-to-supporting-a-netball-athlete",
    title: "A parent's guide to supporting a developing netball athlete",
    excerpt:
      "What actually helps your child become a better netballer, what quietly hurts, and the line that separates the two.",
    date: "2026-05-04",
    readMinutes: 6,
    category: "Mindset",
    body: [
      "Most netball parents I meet are doing more right than they realise. They're driving to training in the rain, packing healthy lunches, learning the rules, and cheering hard on Saturday mornings. The trick is keeping the support strong without crossing into pressure that quietly takes the love of the game away.",
      "Here's what I've seen work, and what I've seen go wrong, after coaching hundreds of athletes from Net Set Go through to senior representative.",
      "## What helps",
      "**Be a great driver, not a great coach.** Your job in the car after the game is to listen, not to break down the third quarter. Ask one open question: 'Did you have fun?' Then leave the analysis to the coach. The athletes who go furthest are the ones whose parents make car rides feel safe to lose, not just to win.",
      "**Watch the effort, not the scoreboard.** Every elite player I know remembers the parents who praised the work, not the result. Try lines like 'I loved how hard you chased that ball' or 'You looked really focused today.' That's gold for a developing athlete.",
      "**Back the coach, even when you disagree.** Athletes can hold one set of instructions in their head per game. If they hear something different from a parent on the sideline, the whole structure collapses. Disagree privately, support publicly.",
      "## What quietly hurts",
      "**Comparing your child to others.** Especially out loud. Especially to their face. Two athletes who develop at completely different rates can both end up in elite programs. Comparison only teaches your child that other athletes are the standard. They aren't.",
      "**Sideline coaching.** Yelling 'pass it', 'shoot', 'mark her' during play forces your athlete to listen to two voices at once. It also signals you don't trust them to make the call. Both kill confidence.",
      "**Outcome-only conversations.** If every chat after netball is about whether they won, scored, or were named in the team, eventually netball stops being theirs. It becomes yours.",
      "## The questions worth asking",
      "Instead of 'Did you win?' or 'How many did you score?', try:",
      "- What did you enjoy about today?\n- What's something you tried that you've been working on?\n- Is there a teammate I should say well done to?",
      "These questions train your child to evaluate their own performance against their own goals, not against external scoreboards. That habit is what separates the kids who plateau from the ones who keep climbing.",
      "## The long view",
      "Athletes peak in netball at very different ages. The early developers often peak first, then plateau. The late bloomers (myself included) often catch and pass them. Whichever camp your child is in, your job is the same: keep the love alive, keep them around the game, and trust the process.",
      "Premier league, state, Diamonds. Those are real targets, but they're decided by what happens between the ages of seventeen and twenty three, not eleven and twelve. Patience is the most underrated parenting skill in netball.",
    ],
  },
  {
    slug: "coming-back-from-an-acl-injury",
    title: "Coming back from an ACL injury: what every netballer should know",
    excerpt:
      "I tore my ACL at twenty and learned to run again. Here's the real story of the recovery, and what I wish someone had told me on day one.",
    date: "2026-05-04",
    readMinutes: 7,
    category: "Performance",
    body: [
      "I ruptured my anterior cruciate ligament at twenty years old. I had surgery, learned how to run again, and a few years later played for the Australian Diamonds. The injury delayed my elite selection by about two years. I'm not the first netballer to do this. I won't be the last.",
      "If you're an athlete in the early days of ACL recovery, or a parent reading this for your daughter, this is the version of the conversation I wish I'd had on day one.",
      "## The first week is the hardest, mentally",
      "Physically, the first week is mostly waiting. You're sore, you're on crutches, the swelling is still going down. You haven't even started rehab. The hardest part is the head.",
      "You'll spend a lot of time scrolling Instagram watching other people play. Don't pretend that doesn't sting. It does. The athletes who recover best are the ones who let themselves feel that for a few days, then redirect that energy into the rehab plan.",
      "## Rehab is the long game (six to nine months minimum)",
      "Modern ACL rehab is around nine to twelve months for full return to sport. Some clubs and leagues will quote shorter, but the science around graft maturation and re-injury risk is clear: rushing back early roughly doubles your re-injury rate.",
      "There are no shortcuts. The athletes who recover best treat their rehab program with the same intensity they used to train at on court. Two physio sessions a week, daily home exercises, gym work, the lot. Boring? Yes. Negotiable? No.",
      "## You'll learn things about your body you'll keep for life",
      "The single quiet gift of ACL recovery is that it forces you to learn how your body actually works. Single leg balance, hip stability, glute activation, landing mechanics. These are the things most netballers never train deliberately until they get hurt. Once you know them, your performance ceiling lifts.",
      "Most of the elite athletes I know who came back from ACLs say they came back fitter and more aware than they were before. That's not a consolation prize. It's the truth.",
      "## Returning to court is not the finish line",
      "Getting cleared to play feels like the end of the journey. It isn't. The first six months back are when re-injury risk is highest. Your knee is structurally fine, but your nervous system is still rebuilding the trust to land, cut, decelerate at full speed.",
      "Manage your loads. If you've been off for nine months, you don't go straight into three trainings and a game per week. You build it. Talk to your physio about a graded return-to-play plan. Talk to your coach about minutes management. The coaches worth playing for will respect this.",
      "## What every netballer (and parent) should know about prevention",
      "ACL injuries in women's netball are roughly four to six times more common than in men's sports of similar load. The reasons are biomechanical and hormonal, and most of them are trainable.",
      "Prehab programs like the netball-specific KNEE program from Netball Australia, or general programs like the FIFA 11+, have been shown to cut ACL injury rates by up to 50 percent when done two to three times a week. Twenty minutes. Twice a week. Half the risk.",
      "If your club isn't running prehab, start it yourself. If you're a parent, ask your coach about it. It's the single highest-leverage thing you can do to protect a netballer's career.",
      "## The closing thought",
      "ACL injuries feel like the end of the world the day they happen. They aren't. They're a long, slow rebuild that, done properly, makes you a better athlete than you were before. I'm not going to say I'm grateful for mine, that would be a stretch. But I am grateful for what it taught me.",
      "Be patient. Trust your physio. Don't rush. The court will still be there.",
    ],
  },
  {
    slug: "behavioural-change-high-performance",
    title:
      "The behavioural change that led to my high-performance selection",
    excerpt:
      "A short, honest reflection on the single shift in habits that opened the door to elite programs.",
    date: "2022-02-07",
    readMinutes: 4,
    category: "Mindset",
    body: [
      "Breaking into high-performance netball programs is hard. With over three hundred thousand registered players in Australia alone, success requires hard work, perseverance, great coaching, unwavering passion, and a thirst for continued growth.",
      "My pivotal realisation during my junior career came down to one thing: the realisation of intent and effort. I wasn't lazy, but I had coasted through training sessions relying on natural ability and only intensifying my performance on game day.",
      "The turning point came at my first Victorian State Netball Trial. The intensity and fitness requirements were significantly higher than what I had experienced. I felt exhausted after the sessions and didn't make the selection that year. The non-selection became my wake-up call.",
      "I needed to work harder and smarter by lifting my work rate during existing sessions, rather than simply adding more training. The principle was simple: train the way I wanted to play. The shift transformed my on-court performance. The improved fitness let me hold concentration longer and execute precise passing and movement.",
      "My message to athletes heading to your next session is to commit to giving 100 percent effort. It benefits not only your individual performance but also lifts your teammates as everyone rises to meet the challenge of competing at higher intensity.",
    ],
  },
  {
    slug: "your-start-does-not-determine-your-finish",
    title: "Your start does not determine how you're going to finish",
    excerpt:
      "Notes on long-term player development, written for athletes who feel they're behind the pack.",
    date: "2021-11-16",
    readMinutes: 4,
    category: "Mindset",
    body: [
      "Non-selection and injuries happen to all of us, including the elite. No-one is immune to this.",
      "We all take a different path in our netball journey, so we need to refrain from comparing ourselves to our peers and what they are doing.",
      "I played for Australia, and I also missed out on Echuca Primary School Grade 5/6 school netball team (when I was in grade 5).",
      "I played for Australia, and I also missed out on every Victorian State Netball team I tried out for as a bottom-age athlete.",
      "I played for Australia, and I also ruptured my Anterior Cruciate Ligament at 20 years of age, required surgery, and had to learn how to run again.",
      "Looking back on my own netball journey there are so many occasions I could have given up and said it was all too hard. I chose to persevere and saw the setbacks as growth opportunities. That doesn't mean I wasn't upset and hurt by these experiences. Trust me, I was. It meant that I chose to stick with my passion, put my best foot forward, and keep working towards my dream.",
      "Whilst there is a clear pathway for netball and how to reach the Australian Diamonds, remember our individual journey is unique. Some players will step through every stage of the pathway. Some players (like myself) go in and out of the pathway at various stages. Others simply enter the pathway as a senior player.",
      "So please be kind to yourself and don't let a setback be the end of your journey.",
      "Caitlyn Nevins",
    ],
  },
  {
    slug: "craft-of-a-goal-keeper",
    title: "The craft of a goal keeper",
    excerpt:
      "Footwork, anticipation, body positioning. Breaking down the discipline of one of netball's hardest positions.",
    date: "2022-01-23",
    readMinutes: 5,
    category: "Position",
    body: [
      "Tara Hinchliffe is an experienced defender in the Suncorp Super Netball competition, set to make her debut with the Sunshine Coast Lightning after four years with the Queensland Firebirds. Tara has demonstrated great resilience and the power of a positive mindset in her rehabilitation following an ACL reconstruction during the 2021 season.",
      "## What do you love most about playing Goal Keeper?",
      "I love the feeling that you have all the time in the world as the ball comes down court towards you. I can anticipate where the attackers will move, and trying to outsmart them is a massive challenge. There is no better feeling than coming out of the circle for a fly and taking a speccy intercept.",
      "## Have you always played in the defence end?",
      "No, I started playing netball as a GA/GS with my sister Maddie and loved that at the time. Eventually, at around 12 years old, I grew taller (and Maddie was a better shooter than me) so I swapped down to the defence end and have never looked back.",
      "## Your mindset and how you have approached your ACL injury has been inspiring. How did you remain positive throughout the rehab process?",
      "I was fortunate to have a lot of perspective at the time. I had been lucky to be playing in the Suncorp Super Netball for four years without any major injuries. COVID was a big concern and I had also watched my sister Maddie miss the whole season with a broken foot that required surgery. I was also surrounded by so much love and support, and knew I would be ok as soon as it happened.",
      "## What are you looking forward to most about the 2022 Suncorp Super Netball season?",
      "I'm really looking forward to seeing what life with the Sunny Coast Lightning is all about. There has also been so much young talent being signed across the league so I can't wait to see what these new players can do.",
      "## What is the best thing about being a professional netball player?",
      "My favourite thing is being able to be out in the community and have a positive influence on little netballers growing up. It doesn't feel like long ago that I was the netty nerd looking up to the elite players at the time. Also being able to play a sport that I love as a job is such a privilege.",
    ],
  },
  {
    slug: "netball-recovery-physio",
    title: "Netball recovery: a sports physio's perspective",
    excerpt:
      "What the science says about recovery for netball athletes, and what most clubs still get wrong.",
    date: "2021-11-26",
    readMinutes: 5,
    category: "Performance",
    body: [
      "Featuring Elyse Nayler, APA Sports and Exercise Physiotherapist (SportsPlus Physiotherapy, Highgate Hill QLD).",
      "Recovery refers to the repair process which starts as soon as you come off the court, or finish training or a game. A good recovery is essential for getting the best possible physical benefits from your physical activity, and for preparing you for your next session.",
      "By far, the most important recovery strategy is to ensure you're getting enough sleep (adolescent athletes may need 8-10+ hours). This is incredibly important. The second most important strategy is to make sure you're rehydrating and refuelling with the correct nutrition.",
      "What else can you do to aid recovery? Stretching, ice baths, compression garments, and cool downs are all extra strategies you can implement to give yourself a small extra edge if you're nailing your sleep and nutrition.",
      "## Cool down or active recovery",
      "Cooling down following training and games helps reduce the perception of muscle soreness and slowly brings your heart rate back to resting state. Ideally include 10-15 minutes of:",
      "- A few slow jogging laps across the court\n- Walking and doing dynamic stretching or range of motion exercises (such as leg swings)\n- Static stretching (the least important element)",
      "## Ice baths, foam rollers and the rest",
      "Ice baths and compression garments have been shown to make athletes feel better recovered if used following training (although there isn't a lot of evidence about the true physiological benefits). Foam rollers, spikey balls and massage guns can be useful if any areas feel tight or mildly sore.",
      "Remember: the most important things are sleep and refuelling. The other strategies don't have much proven physiological effect but work by making you feel as though you're better recovered and fresher the next day.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
